yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name: str = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts'
                               )
    group = models.ForeignKey('Group',
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts'
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время публикации комментария'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Подписка на авторов."""
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follower')
        ]

    def str(self):
        return f"{self.author}, follower:{self.user}"

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", 'image']
        help_texts = {
            "text": "Прописываем текст поста",
            "group": "Группа для опубликования"}
        labels = {
            "text": "Текст поста",
            "group": "Группа"}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import get_paginator


def index(request):
    posts = Post.objects.all()
    template = 'posts/index.html'
    page_obj = get_paginator(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    page_obj = get_paginator(group.posts.all(), request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    template = 'posts/profile.html'
    page_obj = get_paginator(author.posts.all(), request)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(
            user__username=request.user, author__username=username).exists())
    context = {
        'author': author,
        'following': following,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author_posts = post.author.posts.count()
    num_author_posts = Post.objects.filter(author=author_posts).count()
    comment_form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'author_posts': author_posts,
        'posts_count': num_author_posts,
        'form': comment_form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    tamplate = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, tamplate, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/create_post.html'
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.pk)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.pk)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Посты авторов,на которых подписан текущий пользователь, не более 10"""
    user = request.user
    posts = Post.objects.filter(author__following__user=user)
    page_obj = get_paginator(posts, request)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    """Функция отписаться от некого автора"""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% if is_edit %}Редактировать запись{% else %}Новая запись{% endif %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %} 
{% block title %} Подписки {% endblock %}
{% block content %}
<div class="container py-5">
  {% include 'includes/switcher.html' %}
  <h2> Последние обновления авторов, на которых вы подписаны </h2>
  {% for post in page_obj %}
    {% if post.group %}
    {% include 'includes/post.html' %}
    <a class="btn btn-primary btn-sm" href="{% url 'posts:group_list' post.group.slug %}">
      Все записи группы
    </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
Записи сообщества {{ group.slug|title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <p>
    {{ group.description }}
  </p>
  <h1>{{ group.title }}</h1>
  <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      <a href="{% url 'posts:profile' post.author.username %}">
      Все посты пользователя
      </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
      Редактировать запись
    </a>
    <p>
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
    </p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
<div class="container py-5">     
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
  {% comment %} кэш обнавляется раз в 20 сек. {% endcomment %}
  {% load cache %}
  {% cache 20 index_page with page_obj %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      <a href="{% url 'posts:profile' post.author.username %}">
        Все посты пользователя
      </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}     
    <p> {{ post.text }} </p>
    <p>
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
    </p>
    {% if post.group %}
     <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'includes/paginator.html' %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
              Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ author_posts }}
              </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
              Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% load thumbnail %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaks }}
          </p>
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
            {% endif %}
            {% load user_filters %}
            {% if user.is_authenticated %}
              <div class="card my-4">
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                  <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}      
                    <div class="form-group mb-2">
                      {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                  </form>
                </div>
              </div>
            {% endif %}
            <h5>
              {% if comments %}
              Комментарии:  
              {% else %}
              К данному посту пока нет ни одного комментария. Вы можете быть первым
              {% endif %}
            </h5>
            {% for comment in comments %}
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                      {{ comment.author.username }}
                    </a>
                  </h5>
                    <p>
                    {{ comment.text }}
                    </p>
                  </div>
                </div>
            {% endfor %}
        </article>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя! {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="container">   
    <h1>Все посты пользователя: {{ author }} </h1>
    <h3>Всего постов: {{ posts_amount }} </h3>
      {% if following %}
        <a class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
          role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}"
          role="button">Подписаться</a>
      {% endif %} 
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% load thumbnail %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
      {% if post.group %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a></p>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      </article>       
  </div>  
{% endblock %}